# Generated by Django 3.2.25 on 2024-05-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
